version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: screenshot_docs_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - api_uploads:/app/uploads
      - api_outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: screenshot_docs_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: pnpm run dev -- --host
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  api_uploads:
  api_outputs:
